### ISSUE TITLE
Accessing options in save-file event

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#156] opened 2021-05-16 13:51 UTC
Hi,
How can I access `fileType` parameter in `save-file` event in below code?

```js
function handleCreateFile(fileType) {
    basic.createSaveDialog();
}

useEffect(() => {
  basic.on('save-file', selectedData => {
    // I need my fileType here
  });
}, []);

```

**Comment by andersevenrud** [comment] 2021-05-16 14:03
A VFS file object contains `isDirectory`. Can't you use that ?

**Comment by mahsashadi** [comment] 2021-05-16 17:33
Indeed I just pass an extension to handleCreateFile function (odt, odp,...), and then I want It to open save as dialog to create the file with my extension, with path and name set in SaveDialog

**Comment by mahsashadi** [comment] 2021-05-16 17:37
To clarify more, the project is about making new file for office.
I have different buttons for making new word/ powerpoint/ excel files, which all calls handleCreateFile function in their onclick event.

**Comment by andersevenrud** [comment] 2021-05-16 17:52
You could probably create a proxy type event handler for this:

```javascript
function handleCreateFile(fileType) {
  basic.off('save-file') // Just to ensure no duplicate events
  basic.once('save-file', result => basic.emit('my-save-file', result, fileType)
  basic.createSaveDialog()
}

useEffect(() => {
  basic.on('my-save-file', (file, fileType) => {
  })
}, [])
```

**Comment by mahsashadi** [comment] 2021-05-17 06:30
Thanks. 

And how can I filter the files on saveDialog to only show files with my `fileType`?

**Comment by andersevenrud** [comment] 2021-05-17 14:31
What's the value of a `fileType` ?

**Comment by mahsashadi** [comment] 2021-05-17 17:26
It can be an array of strings

For example [“docx”, “odt”] for openjng new file in Office Word, and [“ppt”, “odp”] for Office Powerpoint

**Comment by andersevenrud** [comment] 2021-05-17 17:54
Currently it's only possible to filter with the `mime` option, so you'd have to map your fileType to MIME(s).

**Comment by mahsashadi** [comment] 2021-05-17 18:22
By `mime`, you mean I should define basic like below to work as I need?

```js
  const myBasic = core.make('osjs/basic-application', proc, win, {
    mimeTypes: fileType   //['docx', 'odt', 'txt']
  })
```

**Comment by andersevenrud** [comment] 2021-05-17 18:25
No. MIMEs are formatted like this `foo/bar`.

Ex a `docx` file **extension** is usually the `application/vnd.openxmlformats-officedocument.wordprocessingml.document` MIME **type**.

**Comment by mahsashadi** [comment] 2021-05-17 18:43
So I did not understand how and where I can use them in savedialog senario!

**Comment by andersevenrud** [comment] 2021-05-17 19:07
The basic application usually takes the mime definitions from the metadata file, but you can define these yourself like you demonstrated:

```
const fileTypes = {
  docx: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document']
}

const mimeTypes = Object.values(fileTypes).flat()
const myBasic = core.make('osjs/basic-application', proc, win, {
  mimeTypes
})
```

But since you mention that you want to have different behavior based on what button is clicked, then you probably wanna override the basic application mime types in your dialog. The `mimeTypes` parameter for the basic application is designed to make the dialog accept multiple different MIME types, i.e.`text/plain`+`text/html`,`application/vnd.openxmlformats-officedocument.wordprocessingml.document` files, not separately. I hope that makes sense...

```
const fileTypes = {
  docx: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document']
}

function something(fileType) {
  const mimeTypes = fileTypes[fileType] || []
  basic.createSaveDialog({
    mime: mimeTypes
  })
}
```

So if you need to go for an approach like above here, then you can probably just drop using basic application, because all that it really does is just to handle the session and dialogs anyway.

**Comment by mahsashadi** [comment] 2021-05-17 19:58
Thank a lot for your great explanation :+1
I think the code above works, I will examine more tomorrow.

Just it has problem with one of my drives (loaded by my own adapter) which only has directories (no file) at first level, none of directories are shown.

> So if you need to go for an approach like above here, then you can probably just drop using basic application, because all that it really does is just to handle the session and dialogs anyway.

Since I need a dialog with save-as dialog options I use basic, so why it is better not to use basic in this case?!

**Comment by andersevenrud** [comment] 2021-05-17 20:31
> Since I need a dialog with save-as dialog options I use basic, so why it is better not to use basic in this case?!

Sure, you can just keep using this if it works for you. I just think that maybe once you start to override functionality, maybe it would be best to write it yourself -- if you look at the basic-application source you'll see that there isn't that much going on :) But don't fix what ain't broke, I suppose.

**Comment by mahsashadi** [comment] 2021-05-18 13:55
> maybe it would be best to write it yourself

you are right, I will rewrite this code part again later, thanks a lot.

Just another question , I use `defaultFilename` in below code:

```js
const newBasic = core.make('osjs/basic-application', proc, win, {
        defaultFilename: ' '
    })
```
But from the second time later that I opened it in my app, I have previous used filename. How can I always have empty filename?

**Comment by andersevenrud** [comment] 2021-05-18 14:46
Hm. Sounds like a bug. Can you show screenshots on how to reproduce ?

**Comment by andersevenrud** [comment] 2021-05-18 18:39
> Sounds like a bug

Oh, or maybe not. I'm not 100% sure what you're refering to.

The default behavior of the "basic application" is to store the last used file into the session. So maybe this is what you're getting ?

You can probably override that by doing `proc.args.file = undefined` before `basic.init()`.

**Comment by mahsashadi** [comment] 2021-05-19 05:14
BTW, there is a bug that when I close the save-as dialog by **close button** (not by cancel button), if the **filename textbox has some value**, the **confirm dialog for overwriting is triggered**!
For example It happenes in your textpad application.

**Comment by andersevenrud** [comment] 2021-05-19 20:11
Could you please file an issue about it here https://github.com/os-js/osjs-dialogs/issues ? :)

**Comment by mahsashadi** [comment] 2021-05-22 04:50
> Could you please file an issue about it here https://github.com/os-js/osjs-dialogs/issues ? :)

Sure. It issued [here](https://github.com/os-js/osjs-dialogs/issues/11).

**Comment by andersevenrud** [comment] 2021-05-22 13:22
Please close this issue if you have solved what was asked in OP

**Closed** 2021-06-09 12:13 UTC
Labels: question
